### ISSUE TITLE
CSF, edge, and out masks don't overlap

### ISSUE THREAD

**Issue by catcamacho** [rhr-pruim/ICA-AROMA#13]
I just cloned the repository and it looks like the included maps aren't overlapping correctly. Here is them pulled up in FSLeyes: 
<img width="1176" alt="screenshot 2017-09-27 11 53 31" src="https://user-images.githubusercontent.com/20582555/30923801-e53c252a-a37a-11e7-94db-9278de322924.png">

**Comment by maartenmennes** [comment]
I'm guessing this is related to FSLeyes now actually taking the header information into account. fslview does not do this. 

![image](https://user-images.githubusercontent.com/1139180/30930158-12af7dfe-a3c1-11e7-944b-59ee57ef80d0.png)

This has no further effect on any of the algorithms as they also do not take into account the header information.

**Comment by catcamacho** [comment]
Oh I didn't realize fslview ignore the headers. glad to hear it shouldn't disrupt anything. Thanks!
