### ISSUE TITLE
Components are classified, but no denoising.

### ISSUE THREAD

**Issue by Santoucha** [rhr-pruim/ICA-AROMA#14]
Hi,

I'm running ICA-AROMA on .feat directory with command:
python3 ICA_AROMA.py -feat data.feat -out data.feat/ICA_AROMA/

The pipeline works fine, until at the data denoising. It classifies noise and makes a classified_motion_ICs.txt file, but it says that none of the components were classified as motion...

Here is the log:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Step 3) Data denoising
  - None of the components was classified as motion, so no denoising is applied (a symbolic link to the input file will be created).
Traceback (most recent call last):

  File "/../ICA_AROMA.py", line 215, in <module>
    aromafunc.denoising(fslDir, inFile, outDir, melmix, denType, motionICs)
  File "/../ICA_AROMA_functions.py", line 558, in denoising
    os.symlink(inFile,os.path.join(outDir,'denoised_func_data_nonaggr.nii.gz'))
FileExistsError: [Errno 17] File exists: '/..//filtered_func_data.nii.gz' -> '/../denoised_func_data_nonaggr.nii.gz'

I'm wondering if you have a solution for this problem?

I attached the classified noise files as attachment.
[classified_motion_ICs.txt](https://github.com/rhr-pruim/ICA-AROMA/files/1350629/classified_motion_ICs.txt)
[classification_overview.txt](https://github.com/rhr-pruim/ICA-AROMA/files/1350635/classification_overview.txt)

Hope to hear from you soon.

Kind regards,
Santoucha

**Comment by maartenmennes** [comment]
Hi Santoucha,

not sure what the problem is, but the error message you are receiving suggests that you might have run AROMA a second time on the same dataset? i.e., it indicates that denoised_func_data_nonaggr.nii.gz already exists. I'm guessing that is why it's also indicating that no components were labelled as noise.

Would that be a possibility?

What is the timestamp of the different files in your folder?

**Comment by maartenmennes** [comment]
Can you try with the version I updated today, as this might be related to the indentation issues...

**Comment by Santoucha** [comment]
Yes, it works just fine now! Thanks a lot for looking into this!

Kind regards, 
Santoucha

**Comment by maartenmennes** [comment]
Excellent!
