### ISSUE TITLE
ICA AROMA normalization

### ISSUE THREAD

**Issue by dinadajani** [rhr-pruim/ICA-AROMA#15]
Hello,

I am using ICA-AROMA for motion artefact removal as described in the original Pruim 2015 paper. I minimally preprocess my functional data using the feat gui: motion correction, estimation of linear and nonlinear warping parameters for registration of functional to MNI space (the usual: T1 to EPI with FLIRT and EPI to MNI with FNIRT), and smoothing. I apply ICA-AROMA in native space, and the output is a denoised functional image in native space. Now, I must re-apply the warping parameters estimated in the initial preprocessing to get this denoised image into MNI 152 space. 

Is this the correct pipeline that Pruim et al 2015 proposed (it was unclear to me based on my reading of the paper)? 

& Is below the correct code for applying registration with pre-estimated parameters?

applywarp --ref=${FSLDIR}/data/standard/MNI152_T1_2mm --in=${rest_dir}/ICA_AROMA/denoised_func_data_nonaggr.nii.gz --warp=${rest_dir}/reg/highres2standard_warp --premat=${rest_dir}/reg/example_func2highres.mat --out=${rest_dir}/ICA_AROMA/warped_denoised_func_data_nonaggr.nii.gz

Also, do I need to check the outcome of the functional --> MNI registration again, even though I checked it during preprocessing prior to ICA AROMA? Since I am using the same warping parameters that were generated during preprocessing, should the registration quality be just as good as I saw it in the feat report?

Thank you,
Dina Dajani

**Comment by maartenmennes** [comment]
yes, this is the correct pipeline
yes, that is the correct command
yes, you should always check your data. Even though the parameters did not change, you are resampling your data. This could go wrong in many ways, while this is a rare event, you want to make sure you checked it to avoid having to go on a fishing expedition when something looks off later on in your pipeline. Happy analyzing!

**Comment by dinadajani** [comment]
thanks so much!
