### ISSUE TITLE
set license file

### ISSUE THREAD

**Issue by satra** [rhr-pruim/ICA-AROMA#2]
@rhr-pruim and @maartenmennes - i'm looking to convert this to a nipype workflow. it would be good to set a license on this repo, so others no what can be used and not. i would recommend the Apache2 license.

**Comment by shabtastic** [comment]
Hi @satra: I'm wondering if you all have made any progress regarding this licensing issue. I am very interested in using ICA-AROMA with nipype. Thanks so much!

**Comment by maartenmennes** [comment]
Hello, I've just added the Apache2 license. Thanks for the feedback!
